name: PR Auto Merge on Checks Completion

on:
  check_suite:
    types: [completed]

permissions:
  pull-requests: write
  contents:       write

jobs:
  automerge:
    runs-on: ubuntu-latest
    # Ne traiter que les check_suites liées à une PR du repo
    if: >
      github.event.check_suite.conclusion == 'success' &&
      github.event.check_suite.pull_requests &&
      github.event.check_suite.pull_requests[0].head.repo.full_name == github.repository

    steps:
      - name: Activer l’auto-merge
        uses: peter-evans/enable-pull-request-automerge@v3
        with:
          pull-request-number: ${{ github.event.check_suite.pull_requests[0].number }}
          merge-method: squash
