name: PR Auto Merge

on:
  pull_request_target:
    types: [opened, synchronize, reopened, ready_for_review]

permissions:
  pull-requests: write
  contents: write

jobs:
  automerge:
    runs-on: ubuntu-latest
    # Limit auto-merge to pull requests originating from the same repository
    # (i.e. trusted contributors with push access).
    if: >
      github.event.pull_request.mergeable_state == 'clean' &&
      github.event.pull_request.head.repo.full_name == github.repository
    steps:
      - uses: peter-evans/enable-pull-request-automerge@v3
        with:
          pull-request-number: ${{ github.event.pull_request.number }}
          merge-method: squash
