name: Bump version on merge

on:
  pull_request:
    types:
      - closed

jobs:
  bump:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: ${{ github.event.pull_request.base.ref }}
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Bump version
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          npm version patch -m "chore: bump version to %s [skip ci]"
          git push --follow-tags origin HEAD:${{ github.event.pull_request.base.ref }}
