name: Bump version on merge

on:
  pull_request_target:
    types:
      - closed

jobs:
  bump:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: ${{ github.event.pull_request.base.ref }}
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Bump version
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          version=$(node - <<'NODE'
          const fs = require('fs');
          const path = 'version.json';
          const data = JSON.parse(fs.readFileSync(path, 'utf8'));
          const next = (parseInt(data.version, 10) + 1).toString();
          data.version = next;
          fs.writeFileSync(path, JSON.stringify(data, null, 2));
          console.log(next);
          NODE
          )
          git add version.json
          git commit -m "chore: bump version to v${version} [skip ci]"
          git push origin HEAD:${{ github.event.pull_request.base.ref }}
